### ISSUE TITLE
SBUS Support

### ISSUE THREAD

**Issue by superjax** [rosflight/rosflight_firmware#276]
It would be awesome if we could use FrSky receivers SBUS protocol.

**Comment by superjax** [comment]
Actually, on second thought, this isn't really necessary if we support PPM

**Comment by DaneSlattery** [comment]
discuss.rosflight.org seems to be broken, but rather than opening a new issue, I thought I would just comment here.

http://docs.rosflight.org/en/latest/user-guide/hardware-setup/ says only PPM is supported, but 
http://docs.rosflight.org/en/latest/user-guide/rc-configuration/ says ROSflight only supports PPM receivers on F1 targets while F4 receivers support SBUS and PPM.

Which one is true, and if it is the latter, should the docs reflect this?

**Comment by superjax** [comment]
Thanks for pointing that out.  The latter is correct, F4 targets support sbus while f1 do not.  

Yeah, sorry about the forum being down.  We are working on a new hosting solution and we should be up again soon.

**Comment by superjax** [comment]
I reopened  this to remind me to modify the did to not be confusing.

**Comment by bsutherland333** [comment]
Documentation has already been clarified.
