### ISSUE TITLE
Process for building support for other F4 boards?

### ISSUE THREAD

**Issue by atyshka** [rosflight/rosflight_firmware#304]
I have an F4 Omnibus flight controller and I’m wondering what modifications I’d need to make for rosflight to run on it. The docs seemed to suggest that it should work on any F4, but other places suggested this firmware is very specific to the revo. If it wouldn’t work out of the box, would building support for my board require modifcations to rosflight, airbourne, or both?

**Comment by superjax** [comment]
Hey @atyshka,

Yeah, I didn't do a great job of architecting the code so that it was obvious how to extend airbourne.  

It's a change to airbourne.  In [airbourne/include/revo_f4.h](https://github.com/rosflight/airbourne_f4/blob/master/include/revo_f4.h) I have defined all the peripheral mappings, and that is the only revo-specific code (or at least it _should_ be) in airbourne.

The include structure of airbourne is currently pretty revo-specific, but that's just because I wasn't very careful.  I think the right thing to do is use a macro set at compile time which directs airbourne to the proper header, whether it be the revo, or the omnibus to the proper peripheral mappings.

If I were implementing a new board, I would start by making sure that all of the header files in the `include` folder in airbourne only pointed to the `system.h` header, and add some code to the top of that header which looked something like

``` C++
#if defined(REVO)
#include "revo_f4.h"
#elif defined(OMNIBUS)
#include "omnibus_f4.h"
#else
#error "No compatible board implementation found"
#endif
```

That way the right peripheral mappings get included.

The next thing would be to make a copy of `revo_f4.h` and modify it so that it hooks up everything you need for the omnibus board, and finally, I would build and run each of the examples, to make sure that everything works.

If the examples work, then ROSflight should work, because it uses the API tested by the examples.
