### ISSUE TITLE
ROS2 support via Micro XRCE-DDS / micro-ROS

### ISSUE THREAD

**Issue by christianrauch** [rosflight/rosflight_firmware#328]
Are there plans to support ROS2 via Micro XRCE-DDS in the future?

There are efforts to support resource constrained environments, like MCU, via the micro-ROS project (https://discourse.ros.org/t/rmw-microxrcedds-implementation/6727).

While a plain ROS2 port of the `rosflight` node would already enable ROS2 support, enabling serial communication via micro-ROS / XRCE-DDS directly in the firmware would remove the need for a specific ROS node on a companion computer and allow the flight controller to directly access the ROS2 topics and services.

**Comment by superjax** [comment]
We actually designed ROSflight with an abstract Comm layer specifically for this reason. (see `include/comm_link.h`) (as well as the ability to use other serialization protocols, such as protobuf etc...) but haven't actually implemented anything other than the default MAVlink protocol.  

Micro XRCE-DDS/ROS2 would definitely be interesting.  I personally haven't looked into it much at all, but I think it could simplify a lot of the communications used currently.

If we could still achieve sufficiently high stream rates and keep the implementation clean, then I think it would be a great idea.

No current plans to implement it as of yet, though, mainly due to not enough time.
